language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
before-script:
  - flake8 src/
  - flake8 tests/
# command to run tests
script:
  - pytest -s tests/test.py