[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.idea
  | .gitattributes
  | ./.pytest_cache
  | \tests/__pycache__
  | \src/__pycache__
  | \.tox
  | \venv
  | _build
  | buck-out
  | build
  | dist
)/
'''